#!/usr/bin/env bash
## Install vm
## Global VARS

install_packages="open-vm-tools-desktop vsftpd tftpd-hpa nginx nginx-extras wireshark netcat tcpdump ftp openssh-server git"

## END GLOBAL VARS


if [ `id -u` != "0" ]
        then
                clear
                echo
                echo "You are User $(id)"
                echo
                echo "##########################"
                echo "$0 must run as root"
                echo "Please use sudo ! We need sudo (sudo -i)!"
                echo "Press any key to continue"
                while [ true ] ; do
                    read -t 3 -n 1
                        if [ $? = 0 ] ; then
                            exit 1;
                        fi
                done
fi

if      [[ -z $SUDO_USER ]]
    then
        # Ok SUDO_USER existiert nicht.. wir nehmen einfach den Benutzer mit der UID=1000 zum autologin etc
        export SUDO_USER=$(id -n -u 1000)
fi


#  to configure sudo
configure_sudo () {

cat << EOF > /etc/sudoers.d/$SUDO_USER
cw-support      ALL=(ALL:ALL)   NOPASSWD:ALL
EOF
} # End configure_sudo()

configure_sudo

echo "Install Xfce und VMtools and some Services"
echo "wireshark-common wireshark-common/install-setuid boolean true" | debconf-set-selections
echo "lightdm shared/default-x-display-manager select lightdm" | debconf-set-selections

update_vm () {
#
apt update && apt dist-upgrade -y
tasksel install xfce-desktop
apt install vim $install_packages -y
adduser $SUDO_USER wireshark
clear
echo
echo "#######################################################################"
echo
}

## We will define some s for Customization


configure_lightdm () {
echo "Customize lightdm/lightdm"
## Lightdm autologin
if ! [ -d /etc/lightdm/lightdm.conf.d ]; then
           mkdir -p /etc/lightdm/lightdm.conf.d
fi


cat << EOF > /etc/lightdm/lightdm.conf.d/01_autologin.conf
[Seat:*]
autologin-user=$SUDO_USER
autologin-guest=false
autologin-timeout = 0
Session=xfce

EOF

## dpkg-reconfigure lightdm

dpkg-reconfigure lightdm


}  # End configure_lightdm()



configure_tftp () {
echo "configure tftp"

FILENAME="/etc/default/tftpd-hpa"
SERVICE="tftpd-hpa"
TFTP_USER=$SUDO_USER

## Test if file exists

if [[ -e $FILENAME ]]; then mv $FILENAME{,.bak}; fi
if [[ ! -d /home/$SUDO_USER/data ]] ; then mkdir -p /home/$SUDO_USER/data ; fi
chmod 755 /home/$SUDO_USER/data
chown -R $SUDO_USER:$SUDO_USER /home/$SUDO_USER/data

cat << EOF > $FILENAME
# /etc/default/tftpd-hpa

TFTP_USERNAME="$TFTP_USER"
TFTP_DIRECTORY="/home/$TFTP_USER/data"
TFTP_ADDRESS=":69"
TFTP_OPTIONS="--ipv4 -vvv --create --secure"

EOF

systemctl restart $SERVICE
unset FILENAME SERVICE TFTP_USER

} # End configure_tftp()


configure_ftp () {
## Customize vsftp
export FILENAME="/etc/vsftpd.conf"

echo You are User `id`
if [ `id -u` != "0" ]
        then
                echo "########################## must run as root"
                echo "invoking sudo"
                                sudo -i FILENAME=$FILENAME
fi


# Remark %SUDO_USER is the old $USER
## VSFTP is really picky about permissions
export FTPHOME="/home/$SUDO_USER"

if [[ -e $FILENAME ]]; then mv $FILENAME{,.bak}; fi
if [[ ! -d $FTPHOME/data/upload ]] ; then mkdir -pv $FTPHOME/data/{upload,Downloads}; fi
chown -R $SUDO_USER:$SUDO_USER /home/$SUDO_USER/data
chown 555 /home/$SUDO_USER/data

cat << EOF > $FILENAME
listen=NO
listen_ipv6=YES
anonymous_enable=YES
local_enable=YES
write_enable=YES
local_umask=022
anon_upload_enable=YES
anon_root=/home/$SUDO_USER/data/
no_anon_password=YES
ftp_username=$SUDO_USER
anon_mkdir_write_enable=YES
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
chown_uploads=YES
chown_username=$SUDO_USER
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
ssl_enable=NO


EOF
#
unset FILENAME FTPHOME

} ## End  configure_ftp()




configure_sftp () {
## SFTP Anpassung
# make ~./data to the start path oft sftp-server
#

sed -i 's/sftp-server/sftp-server \-d \%d\/data/' /etc/ssh/sshd_config
systemctl restart sshd
} ## End  configure_sftp



configure_XFCE () {

########################################
# XFCE Powermanagment & Screensafer
# Hier wir der Screensafer und Powersafe im XFCE angepasst.
# Copy und Paste in ein Terminal des Benutzers.
# Dieses Script muss einmal ausgeführt werden.
# Wir erstellen also

if [[ -d /home/$SUDO_USER/Desktop ]]
    then
    Desktop="/home/$SUDO_USER/Desktop"
elif [[ -d /home/$SUDO_USER/Schreibtisch ]]
    then
    Desktop="/home/$SUDO_USER/Schreibtisch"
fi


myFile="/home/$SUDO_USER/XFCE_DISABLE_SCREENSAFER.sh"

if [[ ! -d /home/$SUDO_USER/.config/autostart ]]
then
        mkdir -p /home/$SUDO_USER/.config/autostart
        chown -R $SUDO_USER:$SUDO_USER /home/$SUDO_USER/.config
fi

myAutoStart="/home/$SUDO_USER/.config/autostart/runonce.desktop"

cat <<EOF > $myAutoStart
[Desktop Entry]
Version=0.01
Encoding=UTF-8
Type=Application
Name=XFCE-Customization
Comment=XFCE-Customization
Exec=$myFile
GenericName=XFCE-Customization

[/end Desktop Entry
EOF

chmod 755 $myAutoStart
chown $SUDO_USER:$SUDO_USER $myAutoStart

cat << EOF > $myFile
#!/usr/bin/env bash
clear
echo
echo "XFCE customization"
mySelf=\${0}

if [ \$(id -u) == "0" ]
    then
        echo "You are root"
        echo "This section should be run by a nomal user"
fi

if [[ \$XDG_CURRENT_DESKTOP=="XFCE" ]]
then
echo "invoke xfconf-query ..."
/usr/bin/xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-enabled -s false --create -t bool
/usr/bin/xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/blank-on-ac -s 0 --create -t int
/usr/bin/xfconf-query -c xfce4-session -n -t bool -p /startup/screensaver/enabled -s false --create -t bool
/usr/bin/xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/blank-on-battery -s 0 --create -t int
/usr/bin/xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/inactivity-sleep-mode-on-ac -s 0 --create -t int
/usr/bin/xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/inactivity-sleep-mode-on-battery -s 0 --create -t int
/usr/bin/xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/lock-screen-suspend-hibernate -s false --create -t bool
/usr/bin/xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/logind-handle-lid-switch -s false --create -t bool
/usr/bin/xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/power-button-action -s 0 --create -t int
/usr/bin/xfconf-query -c xfce4-screensaver -p /lock/saver-activation/enabled  -s false --create -t bool
/usr/bin/xfconf-query -c xfce4-screensaver -p /lock/status-messages/enabled   -s false --create -t bool
/usr/bin/xfconf-query -c xfce4-screensaver -p /lock/user-switching/enabled    -s false --create -t bool
/usr/bin/xfconf-query -c xfce4-screensaver -p /saver/enabled                  -s false --create -t bool
/usr/bin/xfconf-query -c xfce4-screensaver -p /lock/enabled -s false --create -t bool
/usr/bin/xfconf-query -c xfce4-screensaver -p /saver/idle-activation/enabled  -s false --create -t bool
/usr/bin/xfconf-query -c xfce4-screensaver -p /saver/mode                    -s  0 --create -t int


fi
# Anpassung an die XSession
echo "xset dpms 0 0 0" >> \$HOME/.xsessionrc
echo "xset -dpms " >> \$HOME/.xsessionrc
echo "xset s off" >> \$HOME/.xsessionrc
echo 'setxkbmap -layout "de" -variant "nodeadkeys" ' >> \$HOME/.xsessionrc

# anpassung ssh
echo "generate ssh keys"
ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1

##

## delete me mysel
if [[ -e $myAutoStart ]] ; then rm -rf $myAutoStart; fi
rm -rf \$mySelf
systemctl reboot
EOF

chown $SUDO_USER:$SUDO_USER $myFile
chmod 755 $myFile
} # Ende XFCE anpassung

configure_ssh () {
echo "generate ssh keys"
ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
}

configure_vmware_mount () {
## Anpassungung vmware Mount
echo "VMWare Workstation kann eine locales Verzeichniss mounten. Hierzu sind die open-vm-tools-desktop notwendig
In Vmware Worksation geht man wie Folgt vor:

cw-support-vm > Settings > Options > Shared Folders
        * Always Enable Auswählen
        * Add > HostPath == C:\Users\%USERNAME%\Downloads
                * Name sollte automatisch 'Downloads' heißen
        * Next > Enable this Share auswählen  > Finish

Wir setzen jedenfalls den Mount-Point auf /home/$SUDO_USER/data/Downloads

"

if [[ ! -d /home/$SUDO_USER/data/Downloads ]] ; then mkdir -pv /home/$SUDO_USER/data/Downloads; fi
chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/data/Downloads
chmod 755 /home/$SUDO_USER/data/Downloads


echo ".host:/Downloads /home/$SUDO_USER/data/Downloads fuse.vmhgfs-fuse noauto,defaults,allow_other 0 0" >> /etc/fstab
echo "user_allow_other" >> /etc/fuse.conf

} # End $SU configure_vmware_mount

clean_up () {
## Clean up
echo "Cleanup"
apt auto-remove -y
apt-get clean
}

configure_nginx () {
    # Hier wird der Nginx Dienst angepasst
    systemctl stop nginx
    # delete the link for the default webseite
    rm /etc/nginx/sites-enabled/default
cat << EOF > /etc/nginx/sites-enabled/support-vm
   server {
    server_name _;
       listen 80 default_server;
    listen [::]:80 default_server;
    # SSL configuration
    #
     listen 443 ssl default_server;
     listen [::]:443 ssl default_server;
    #
    # Self signed certs generated by the ssl-cert package
    # Don't use them in a production server!
    #
    include snippets/snakeoil.conf;
    index index.html;
    root /home/$SUDO_USER/data;
       location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            root /home/$SUDO_USER/data;
            autoindex on;
            autoindex_exact_size        off;
            autoindex_localtime off;

            autoindex_format xml;
            xslt_stylesheet /home/$SUDO_USER/data/autoindex.xslt;
            # add upload
            dav_methods PUT DELETE MKCOL COPY MOVE;
            add_header X-Options "WebDav";
            create_full_put_path on;
            dav_access  all:r;
            client_body_temp_path      /home/$SUDO_USER/temp;
            client_body_in_file_only   on;
            client_body_buffer_size    128K;
            client_max_body_size       10G;
        }
           location /upload {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                autoindex on;
                autoindex_exact_size    off;
                autoindex_localtime off;

                autoindex_format xml;
                xslt_stylesheet /home/$SUDO_USER/data/autoindex.xslt;
                # add upload
                dav_methods PUT DELETE MKCOL COPY MOVE;
                add_header X-Options "WebDav";
                create_full_put_path on;
                dav_access      all:rw;
                client_body_temp_path      /home/$SUDO_USER/temp;
                client_body_in_file_only   on;
                client_body_buffer_size    128K;
                client_max_body_size       10G;
        }
    }

EOF

# Ende /etc/nginx/sites-enabled/support-vm

#  Stylesheet for dir listing und dav
cat << EOF > /home/$SUDO_USER/data/autoindex.xslt
<?xml version="1.0" encoding="UTF-8" ?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="UTF-8" />

<xsl:template match="/">
  <xsl:text disable-output-escaping="yes">&lt;!DOCTYPE html&gt;</xsl:text>

  <html>
    <head>
      <title>DropZone</title>
        <script src="https://kit.fontawesome.com/55eb9c16a8.js"></script>
        <script type="text/javascript"><![CDATA[
                document.addEventListener('DOMContentLoaded', function(){

                    function calculateSize(size)
                    {
                        var sufixes = ['B', 'KB', 'MB', 'GB', 'TB'];
                        var output = size;
                        var q = 0;

                        while (size / 1024 > 1)
                        {
                                size = size / 1024;
                                q++;
                        }

                        return (Math.round(size * 100) / 100) + ' ' + sufixes[q];
                    }

                    if (window.location.pathname == '/')
                    {
                        document.querySelector('.directory.go-up').style.display = 'none';
                    }

                    var path = window.location.pathname.split('/');
                    var nav = document.querySelector("nav#breadcrumbs ul");
                    var pathSoFar = '';

                    for (var i=1; i<path.length-1; i++)
                    {
                        pathSoFar += '/' + path[i];
                        nav.innerHTML += '<li><a href="' + encodeURI(pathSoFar)  + '">' + path[i] + '</a></li>';
                    }

                    var mtimes = document.querySelectorAll("table#contents td.mtime a");

                    for (var i=0; i<mtimes.length; i++)
                    {
                        var mtime = mtimes[i].textContent;
                        if (mtime)
                        {
                            var d = new Date(mtime);
                            mtimes[i].textContent = d.toLocaleString();
                        }
                    }

                    var sizes = document.querySelectorAll("table#contents td.size a");

                    for (var i=0; i<sizes.length; i++)
                    {
                        var size = sizes[i].textContent;
                        if (size)
                        {
                            sizes[i].textContent = calculateSize(parseInt(size));
                        }
                    }

                }, false);
        ]]></script>

        <script type="text/javascript"><![CDATA[
                document.addEventListener("DOMContentLoaded", function() {

                    var xhr = new XMLHttpRequest();
                    xhr.open('GET', document.location, true);
                    xhr.send(null);

                    xhr.addEventListener('readystatechange', function(e) {
                        if (xhr.readyState == 4) {
                            var headers = parseHttpHeaders(xhr.getAllResponseHeaders().toLowerCase());

                            if (!headers.hasOwnProperty('x-options')){
                                document.body.classList.add('nowebdav');
                            }
                        }
                    });

                    var dropArea = document.getElementById('droparea');
                    var progressWin = document.getElementById('progresswin');
                    var progressBar = document.getElementById('progressbar');
                    var progressTrack = [];
                    var totalFiles = 0;

                    ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
                        dropArea.addEventListener(eventName, function (e){
                            e.preventDefault();
                            e.stopPropagation();
                        }, false);
                    });

                    ['dragenter', 'dragover'].forEach(eventName => {
                        dropArea.addEventListener(eventName, function(e) {
                            dropArea.classList.add('highlight');
                        }, false);
                    });

                    ['dragleave', 'drop'].forEach(eventName => {
                        dropArea.addEventListener(eventName, function(e) {
                            dropArea.classList.remove('highlight')
                        }, false);
                    });

                    document.querySelectorAll('table#contents tr td.actions ul li a[data-action]').forEach(el => {
                        el.addEventListener('click', function(e) {
                            e.preventDefault();
                            e.stopPropagation();

                            var source = event.target || event.srcElement;
                            var action = source.getAttribute('data-action');
                            var href = source.getAttribute('href');

                            if (action == 'delete') {
                                deleteFile(href);
                            }

                        }, false);
                    });

                    dropArea.addEventListener('drop', function(e) {
                        var total = 0;

                        for (var i=0; i<e.dataTransfer.files.length; i++) {
                            var file = e.dataTransfer.files[i];
                            progressTrack[i] = { current: 0, max: file.size };
                            total += file.size;
                            totalFiles++;
                            uploadFile(file, i);
                        }

                        progressBar.value = 0;
                        progressBar.max = total;
                        progressWin.classList.add('show');
                    }, false);

                    function updateProgress(value, idx) {
                        progressTrack[idx].value = value;

                        var current = 0;
                        for (var i=0; i<progressTrack.length; i++) {
                            current += progressTrack[i].value;
                        }

                        progressBar.value = current || progressBar.value;
                    }

                    function uploadFile(file, idx) {
                        var xhr = new XMLHttpRequest();
                        var formData = new FormData();

                        xhr.open('PUT', document.location.href + '/' + file.name, true);
                        xhr.upload.addEventListener("progress", function(e) {
                            updateProgress(e.loaded, idx);
                        });

                        xhr.addEventListener('readystatechange', function(e) {
                            if (xhr.readyState == 4 && (xhr.status == 200 || xhr.status == 201 || xhr.status == 204)) {
                                totalFiles--;
                            } else if (xhr.readyState == 4) {
                                alert (xhr.statusText);
                                console.log(xhr);
                                totalFiles--;
                            }

                            if (totalFiles == 0) {
                                document.location.reload();
                            }
                        });

                        xhr.setRequestHeader('Content-Type', 'application/octet-stream');
                        xhr.send(file);
                    }

                    function deleteFile(path) {
                        if (confirm('Are you sure you want to delete [' + path + ']?')) {
                                var xhr = new XMLHttpRequest();
                                xhr.open('DELETE', document.location.href + '/' + path, true);
                                xhr.send();
                                xhr.addEventListener('readystatechange', function(e) {

                                        if (xhr.readyState == 4 && (xhr.status == 200 || xhr.status == 201 || xhr.status == 204)) {
                                                document.location.reload();
                                        }
                                });
                        }
                    }

                    function parseHttpHeaders(httpHeaders) {
                        return httpHeaders.split("\n").map(x=>x.split(/: */,2)).filter(x=>x[0]).reduce((ac, x)=>{ac[x[0]] = x[1];return ac;}, {});
                    }
                });
        ]]></script>

        <style type="text/css"><![CDATA[
                * { box-sizing: border-box; }
                html { margin: 0px; padding: 0px; height: 100%; width: 100%; }
                body { background-color: #303030; font-family: Verdana, Geneva, sans-serif; font-size: 14px; padding: 20px; margin: 0px; height: 100%; width: 100%; }

                table#contents td a { text-decoration: none; display: block; padding: 10px 30px 10px 30px; pointer: default; }
                table#contents { width: 50%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-width: 0px; }
                table#contents td { padding: 0px; word-wrap: none; white-space: nowrap; }
                table#contents td.icon, table td.size, table td.mtime, table td.actions { width: 1px; white-space: nowrap; }
                table#contents td.icon a { padding-left: 0px; padding-right: 5px; }
                table#contents td.name a { padding-left: 5px; }
                table#contents td.size a { color: #9e9e9e }
                table#contents td.mtime a { padding-right: 0px; color: #9e9e9e }
                table#contents tr * { color: #efefef; }
                table#contents tr:hover * { color: #c1c1c1 !important; }
                table#contents tr.directory td.icon i { color: #FBDD7C !important; }
                table#contents tr.directory.go-up td.icon i { color: #BF8EF3 !important; }
                table#contents tr.separator td { padding: 10px 30px 10px 30px }
                table#contents tr.separator td hr { display: none; }
                table#contents tr td.actions ul { list-style-type: none; margin: 0px; padding: 0px; visibility: hidden; }
                table#contents tr td.actions ul li { float: left; }
                table#contents tr:hover td.actions ul { visibility: visible; }
                table#contents tr td.actions ul li a { display: inline; padding: 10px 10px 10px 10px !important; }
                table#contents tr td.actions ul li a:hover[data-action='delete'] { color: #c90000 !important; }
                body.nowebdav table#contents tr td.actions ul { display: none !important; }

                nav#breadcrumbs { margin-bottom: 50px; display: flex; justify-content: center; align-items: center; }
                nav#breadcrumbs ul { list-style: none; display: inline-block; margin: 0px; padding: 0px; }
                nav#breadcrumbs ul .icon { font-size: 14px; }
                nav#breadcrumbs ul li { float: left; }
                nav#breadcrumbs ul li a { color: #FFF; display: block; background: #515151; text-decoration: none; position: relative; height: 40px; line-height: 40px; pa
dding: 0 10px 0 5px; text-align: center; margin-right: 23px; }
                nav#breadcrumbs ul li:nth-child(even) a { background-color: #525252; }
                nav#breadcrumbs ul li:nth-child(even) a:before { border-color: #525252; border-left-color: transparent; }
                nav#breadcrumbs ul li:nth-child(even) a:after { border-left-color: #525252; }
                nav#breadcrumbs ul li:first-child a { padding-left: 15px; -moz-border-radius: 4px 0 0 4px; -webkit-border-radius: 4px; border-radius: 4px 0 0 4px; }
                nav#breadcrumbs ul li:first-child a:before { border: none; }
                nav#breadcrumbs ul li:last-child a { padding-right: 15px; -moz-border-radius: 0 4px 4px 0; -webkit-border-radius: 0; border-radius: 0 4px 4px 0; }
                nav#breadcrumbs ul li:last-child a:after { border: none; }
                nav#breadcrumbs ul li a:before, nav#breadcrumbs ul li a:after { content: ""; position: absolute; top: 0; border: 0 solid #515151; border-width: 20px 10px;
 width: 0; height: 0; }
                nav#breadcrumbs ul li a:before { left: -20px; border-left-color: transparent; }
                nav#breadcrumbs ul li a:after { left: 100%; border-color: transparent; border-left-color: #515151; }
                nav#breadcrumbs ul li a:hover { background-color: #6320aa; }
                nav#breadcrumbs ul li a:hover:before { border-color: #6320aa; border-left-color: transparent; }
                nav#breadcrumbs ul li a:hover:after { border-left-color: #6320aa; }
                nav#breadcrumbs ul li a:active { background-color: #330860; }
                nav#breadcrumbs ul li a:active:before { border-color: #330860; border-left-color: transparent; }
                nav#breadcrumbs ul li a:active:after { border-left-color: #330860; }

                div#droparea { height: 100%; width: 100%; border: 5px solid transparent; padding: 10px; }
                div#droparea.highlight { border: 5px dashed #CACACA; }

                div#progresswin { position: absolute; left: 0px; top: 0px; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.8); z-index: 10000; justify-conten
t: center; align-items: center; display: none; }
                div#progresswin.show { display: flex !important; }
                div#progresswin progress#progressbar { width: 25%; }
        ]]></style>
    </head>
    <body>
      <div id="progresswin">
        <progress id="progressbar"></progress>
      </div>
      <div id="droparea">
              <nav id="breadcrumbs"><ul><li><a href="/"><i class="fa fa-home"></i></a></li></ul></nav>
              <table id="contents">
                <tbody>
                    <tr class="directory go-up">
                      <td class="icon"><a href="../"><i class="fa fa-arrow-up"></i></a></td>
                      <td class="name"><a href="../">..</a></td>
                      <td class="size"><a href="../"></a></td>
                      <td class="mtime"><a href="../"></a></td>
                      <td class="actions"><a href="../"></a></td>
                    </tr>

                  <xsl:if test="count(list/directory) != 0">
                    <tr class="separator directories">
                      <td colspan="4"><hr/></td>
                    </tr>
                  </xsl:if>

                  <xsl:for-each select="list/directory">
                    <tr class="directory">
                      <td class="icon"><a href="{.}/"><i class="fa fa-folder"></i></a></td>
                      <td class="name"><a href="{.}/"><xsl:value-of select="." /></a></td>
                      <td class="size"><a href="{.}/"></a></td>
                      <td class="mtime"><a href="{.}/"><xsl:value-of select="./@mtime" /></a></td>
                      <td class="actions"><a href="{.}/"></a></td>
                    </tr>
                  </xsl:for-each>

                  <xsl:if test="count(list/file) != 0">
                    <tr class="separator files">
                      <td colspan="4"><hr/></td>
                    </tr>
                  </xsl:if>

                  <xsl:for-each select="list/file">
                    <tr class="file">
                      <td class="icon"><a href="{.}" download="{.}"><i class="fa fa-file"></i></a></td>
                      <td class="name"><a href="{.}" download="{.}"><xsl:value-of select="." /></a></td>
                      <td class="size"><a href="{.}" download="{.}"><xsl:value-of select="./@size" /></a></td>
                      <td class="mtime"><a href="{.}" download="{.}"><xsl:value-of select="./@mtime" /></a></td>
                      <td class="actions">
                        <ul>
                                <li><a href="{.}" data-action="delete" class="fa fa-trash"></a></li>
                        </ul>
                      </td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
        </div>
    </body>
  </html>
</xsl:template>
 </xsl:stylesheet>

EOF

# Ende Stylesheet

chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/data/autoindex.xslt
## need nginx to run as $SUDO_USER
NGINX_CONF="/etc/nginx/nginx.conf"
sed -i "s/www-data/$SUDO_USER/" $NGINX_CONF

systemctl start nginx
}


configure_time_date () {
# in case where default lang an tz was used
apt-get install language-pack-de -y
localectl set-x11-keymap de pc105 nodeadkeys compose:rwin 
timedatectl set-timezone 'Europe/Berlin'

sed -i 's|http://us.|http://de.|g' /etc/apt/sources.list
}


# main
update_vm
## global configuration
configure_lightdm
configure_tftp
configure_ftp
configure_sftp
configure_vmware_mount
configure_time_date

# configure user
configure_XFCE
configure_nginx
clean_up
systemctl reboot

# EOF
